language: node_js

node_js:
  - "10"

branches:
  only:
  - master

script:
  - npm install
  - cd client
  - npm install
  - npm run build
  - npm test
  - cd ..

deploy:
  - provider: heroku
    api_key: $HEROKU_API_KEY
    app: emoji-chat-server-rtangirala
    skip_cleanup: true
  - provider: surge
    project: ./client/build/
    domain: emoji-chat.surge.sh
    skip_cleanup: true
